# Numpy

In [5]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [1]:
import numpy as np

In [2]:
# 배열 확인 함수
def printinfo(array):
    print("shape : {} , dimension :{}, dtype : {}".format(array.shape, array.ndim, array.dtype))

# Numpy array
1) array
2) zeros, ones, empty
3) arange

###  1) array

In [3]:
# - 1D array
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [7]:
array.shape # shape
type(array)  # type
array.ndim # dimension
array.dtype # data type
printinfo(array)

(5,)

numpy.ndarray

1

dtype('int32')

shape : (5,) , dimension :1, dtype : int32


In [8]:
# 2D array
list = [[1,2,3],[4,5,6]]
array2 = np.array(list, dtype=float)
array2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
printinfo(array2)

shape : (2, 3) , dimension :2, dtype : float64


In [11]:
# 3D array
array3 = np.array([[[1,2,3], [4,5,6]], [[1,2,3],[4,5,6]]], dtype=float)
array3

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]]])

In [15]:
printinfo(array3)

shape : (2, 2, 3) , dimension :3, dtype : float64


## 2) ones, zeros, empty
- ones : 어레이 데이터 값이 전부 1
- zeros : 전부 0
- empty : 메모리에서 초기화되지 않은 값을 가져옴

In [20]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [22]:
np.zeros(((1,2,3)))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
one_array = np.ones((2,3))
one_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
printinfo(one_array)

shape : (2, 3) , dimension :2, dtype : float64


In [23]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## 3) arange
- 0~ n-1 까지 배열
- (a, b, c) : a~b-1까지 c씩 건너띄어서

In [26]:
array4 = np.arange(10)
array4
printinfo(array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

shape : (10,) , dimension :1, dtype : int32


# ndarray 타입 변환 : astype()

In [34]:
# 정수형 -> 실수형 데이터 배열로 변환
arr_int = np.array([1,2,3,4,5])

In [29]:
arr_int.dtype

dtype('int32')

In [30]:
arr_float = arr_int.astype(np.float64)
arr_float.dtype

dtype('float64')

In [31]:
# 문자형 -> 정수형
arr_str = np.array(['1','2','3'])
arr_str.dtype

dtype('<U1')

In [33]:
arr_int = arr_str.astype(np.int64)
arr_int.dtype
arr_int

dtype('int64')

array([1, 2, 3], dtype=int64)

## ndarry 차원/크기 변경 : reshape()

In [35]:
# 1차원 -> 2D
arr1  = np.arange(10)
arr1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr2 = arr1.reshape((2,5))
arr2  # 개수는 맞춰서 차원 변경해야함 2행 5열

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
# 2차원 이상 -> 1차원
# 인수 -1
arr2.reshape(-1)

# flatten
arr2.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# reshape(-1, 1) : 맞추고 싶은 조건(행 or 열만 지정해주고, 나머지는 알아서 해줘라(-1))
# reshape(-1,) 

In [40]:
arr2 = arr1.reshape(-1,1)   # 1열
arr2
arr2.ndim

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

2

In [42]:
arr3 = arr2.reshape(-1)
arr3
arr3.ndim

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

1

## ndarray 데이터 선택하기 : 인덱싱(indexing)
### 단일 값 추출
- 1차원 ndarray 인덱싱

In [44]:
arr = np.arange(1,10)
arr
arr[1]
arr[-1]
arr[-2]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

2

9

8

- 2차원 ndarray 인덱싱

In [45]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr[0, 0]
arr[0, 1]
arr[2, 2]

1

2

9

- 1차원 슬라이싱

In [49]:
arr[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr[2:3]

array([[7, 8, 9]])

- 2차원 슬라이싱

In [52]:
arr[1:, :2]

array([[4, 5],
       [7, 8]])

## fancy indexing
- 리스트 / ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray값 반환
- 리턴 값 array

In [53]:
# 1차원
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr[[2, 4, 7]]  # 2열 4열 7열

array([3, 5, 8])

In [57]:
# 2차원
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr[[0,1], 2]  # 0행 1행에서 2열 위치 값

array([3, 6])

In [59]:
arr[[0,1], 0:2] # 0행 1행 0열~1열 

array([[1, 2],
       [4, 5]])

# Boolean indexing
- 조건에 True에 해당하는 인덱스 위치에 있는 ndarray 값 반환
- ndarray내에서 5보다 큰 값 추출하기!

In [60]:
# boolean 안쓸때
arr = np.arange(1, 10)
target = []

for i in range(0, 9):
    if arr[i] > 5:
        target.append(i)

result = np.array(target)
result

array([5, 6, 7, 8])

In [62]:
# boolean indexing
arr = np.arange(1, 10)
arr > 5
arr[arr>5]  # 조건식을 넣고 한번더 감싸준다.

array([False, False, False, False, False,  True,  True,  True,  True])

array([6, 7, 8, 9])

In [63]:
# 조건에 not 취하는 경우 ~
arr[~(arr>5)]

array([1, 2, 3, 4, 5])

# ndarray 배열의 연산
- 1) 기본 연산자/ 함수(사칙연산/ add subtract multiply divide)
  2) dot(내적) -> 행렬의 곱 

In [64]:
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

In [65]:
# 사칙연산
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [66]:
# 사칙연산
np.add(arr1, arr2)

array([[ 6,  8],
       [10, 12]])

In [67]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [68]:
np.multiply(arr1, arr2)

array([[ 5, 12],
       [21, 32]])

### dot 연산
    - 내적
    - (a * b) dot (b * c) -> (a * c) 

In [69]:
# 배열연산
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

In [70]:
arr1.shape

(2, 2)

In [71]:
arr2.shape

(2, 2)

In [72]:
# dot 내적
arr1.dot(arr2)

array([[19, 22],
       [43, 50]])

In [73]:
# 내적
np.dot(arr1, arr2)

array([[19, 22],
       [43, 50]])

## ndarray 배열의 선형대수 연산 - 전치 행렬

In [74]:
arr = np.array([1, 2, 3, 4]).reshape(2, 2)
arr

array([[1, 2],
       [3, 4]])

In [75]:
np.transpose(arr)

array([[1, 3],
       [2, 4]])

In [ ]:
arr = np.array(